#!/bin/bash

for p in $(seq 1 33)
do
  python deep_learning_object_detection.py \
    --prototxt MobileNetSSD_deploy.prototxt.txt \
    --model MobileNetSSD_deploy.caffemodel \
    --image ../yolo-object-detection/images/game$(printf %.2d ${p}).jpg \
    -n -s ;
done

cat << TESTSSD > /tmp/testssdgame.txt
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game01.jpg: person: 73.77%
[INFO] ../yolo-object-detection/images/game01.jpg: person: 60.57%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game01.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game02.jpg: person: 99.83%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game02.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game03.jpg: person: 96.60%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game03.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game04.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game05.jpg: person: 89.33%
[INFO] ../yolo-object-detection/images/game05.jpg: person: 84.45%
[INFO] ../yolo-object-detection/images/game05.jpg: sheep: 98.32%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game05.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game06.jpg: person: 99.99%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game06.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game07.jpg: bicycle: 37.39%
[INFO] ../yolo-object-detection/images/game07.jpg: person: 79.08%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game07.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game08.jpg: chair: 33.15%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game08.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game09.jpg: cow: 76.10%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game09.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game10.jpg: person: 99.97%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game10.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game11.jpg: person: 99.32%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game11.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game12.jpg: person: 71.79%
[INFO] ../yolo-object-detection/images/game12.jpg: tvmonitor: 96.62%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game12.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game13.jpg: person: 79.27%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game13.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game14.jpg: person: 81.54%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game14.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game15.jpg: person: 95.09%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game15.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game16.jpg: person: 99.98%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game16.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game17.jpg: bottle: 78.98%
[INFO] ../yolo-object-detection/images/game17.jpg: person: 38.26%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game17.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game18.jpg: person: 97.50%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game18.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game19.jpg: dog: 67.53%
[INFO] ../yolo-object-detection/images/game19.jpg: person: 82.98%
[INFO] ../yolo-object-detection/images/game19.jpg: person: 34.67%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game19.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game20.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game21.jpg: person: 99.55%
[INFO] ../yolo-object-detection/images/game21.jpg: person: 94.48%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game21.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game22.jpg: person: 99.20%
[INFO] ../yolo-object-detection/images/game22.jpg: person: 75.25%
[INFO] ../yolo-object-detection/images/game22.jpg: person: 30.19%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game22.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game23.jpg: motorbike: 51.15%
[INFO] ../yolo-object-detection/images/game23.jpg: person: 87.89%
[INFO] ../yolo-object-detection/images/game23.jpg: person: 83.62%
[INFO] ../yolo-object-detection/images/game23.jpg: person: 70.39%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game23.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game24.jpg: diningtable: 56.69%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game24.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game25.jpg: person: 44.31%
[INFO] ../yolo-object-detection/images/game25.jpg: person: 41.47%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game25.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game26.jpg: car: 96.78%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game26.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game27.jpg: person: 98.93%
[INFO] ../yolo-object-detection/images/game27.jpg: person: 60.84%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game27.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game28.jpg: chair: 84.42%
[INFO] ../yolo-object-detection/images/game28.jpg: chair: 58.38%
[INFO] ../yolo-object-detection/images/game28.jpg: diningtable: 70.99%
[INFO] ../yolo-object-detection/images/game28.jpg: person: 38.72%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game28.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game29.jpg: car: 26.60%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game29.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game30.jpg: pottedplant: 55.46%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game30.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game31.jpg: diningtable: 67.86%
[INFO] ../yolo-object-detection/images/game31.jpg: sofa: 63.32%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game31.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game32.jpg: person: 48.54%
[INFO] ../yolo-object-detection/images/game32.jpg: train: 40.99%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game32.jpg
[INFO] loading model...
[INFO] computing object detections...
[INFO] ../yolo-object-detection/images/game33.jpg: person: 54.89%
[INFO] ../yolo-object-detection/images/game33.jpg: person: 29.62%
[INFO] saving detection image as ../yolo-object-detection/output/ssd_game33.jpg
TESTSSD
